### ISSUE TITLE
gitcache location not configurable

### ISSUE THREAD

**Issue by codemedic** [jacebrowning/gitman#155]
Thanks for this lovely tool.

I have a minor niggle that I would like to get fixed.

When running `gitman` from within a docker container (where most of the "trusted" *NIX environment variables are missing by default), `"~/.gitcache"` expands to `"/.gitcache"` which then I am having trouble writing to. (Ref: `git.py` line `23`, `os.path.expanduser("~/.gitcache"`). Please note that I am running the container as a low privileged user, so that it doesn't mess up my working directory.

As a workaround, I can pass in or set HOME directory, but it would be ideal if a "no-cache" mode and/or option to specify the cache location would work better.

PS: Unfortunately, I don't do python, otherwise I would have got stuck in.

**Comment by jacebrowning** [comment]
> a "no-cache" mode 

I'd rather avoid this for now, because it's a more invasive change.

> an option to specify the cache location

This seems perfectly reasonable to me. I'm thinking that GitMan could look for this setting in an environment variable named something like:

- `GIT_CACHE`
- `GITMAN_CACHE`
- `GITMAN_CACHE_DIR`

which would default to `~/.gitcache` if unset. Do you have any preference on the environment variable name?

**Comment by codemedic** [comment]
Wonderful  ... sorry I didn't get back with a preference; had a manic week.

**Comment by codemedic** [comment]
@jacebrowning 
It works beautifully! I have created a docker image for it.
https://hub.docker.com/r/redmatter/gitman

Any chance to release this fix soon? I was hoping to have a tagged version in the docker image.
Thanks

**Comment by jacebrowning** [comment]
`GitMan==v1.4` is now released.
